import {Catalog} from 'react-planner';

let catalog = new Catalog();

import * as Items from './items/**/planner-element.jsx';

for( let x in Items ) catalog.registerElement( Items[x] );

catalog.registerCategory('base-units', 'Base Units', [ catalog.registerCategory('single-base-unit', 'Single Base Unit', [Items.singleBaseUnit200, Items.singleBaseUnit250, Items.singleBaseUnit300, Items.singleBaseUnit350, Items.singleBaseUnit400, Items.singleBaseUnit450, Items.singleBaseUnit500, Items.singleBaseUnit550, Items.singleBaseUnit600]), catalog.registerCategory('double-base-unit', 'Double Base Unit', [Items.doubleBaseUnit650, Items.doubleBaseUnit700, Items.doubleBaseUnit750, Items.doubleBaseUnit800, Items.doubleBaseUnit850, Items.doubleBaseUnit900, Items.doubleBaseUnit950, Items.doubleBaseUnit1000, Items.doubleBaseUnit1050, Items.doubleBaseUnit1100, Items.doubleBaseUnit1150, Items.doubleBaseUnit1200]), catalog.registerCategory('corner-base-unit', 'Corner Base Unit', [Items.cornerBaseUnit750, Items.cornerBaseUnit800, Items.cornerBaseUnit850, Items.cornerBaseUnit900, Items.cornerBaseUnit950, Items.cornerBaseUnit1000, Items.cornerBaseUnit1050, Items.cornerBaseUnit1100, Items.cornerBaseUnit1150, Items.cornerBaseUnit1200]), catalog.registerCategory('larder-unit', 'Larder Unit', [Items.larderUnit300, Items.larderUnit350, Items.larderUnit400, Items.larderUnit450, Items.larderUnit500, Items.larderUnit550, Items.larderUnit600]), catalog.registerCategory('drawer-pack', 'Drawer Pack', [Items.drawerPack300, Items.drawerPack350, Items.drawerPack400, Items.drawerPack450, Items.drawerPack500, Items.drawerPack550, Items.drawerPack600]), catalog.registerCategory('tray-space', 'Tray Space', [Items.traySpace100, Items.traySpace150, Items.traySpace200, Items.traySpace250]), catalog.registerCategory('blank-end-corner-base-unit', 'Blank End Corner Base Unit', [Items.blankEndCornerBaseUnit900, Items.blankEndCornerBaseUnit950, Items.blankEndCornerBaseUnit1000, Items.blankEndCornerBaseUnit1050, Items.blankEndCornerBaseUnit1100, Items.blankEndCornerBaseUnit1150, Items.blankEndCornerBaseUnit1200, Items.blankEndCornerBaseUnit1250]) ] );
catalog.registerCategory('wall-units', 'Wall Units', [ catalog.registerCategory('single-wall-unit', 'Single Wall Unit', [Items.singleWallUnit200, Items.singleWallUnit250, Items.singleWallUnit300, Items.singleWallUnit350, Items.singleWallUnit400, Items.singleWallUnit450, Items.singleWallUnit500, Items.singleWallUnit550, Items.singleWallUnit600]), catalog.registerCategory('double-wall-unit', 'Double Wall Unit', [Items.doubleWallUnit650, Items.doubleWallUnit700, Items.doubleWallUnit750, Items.doubleWallUnit800, Items.doubleWallUnit850, Items.doubleWallUnit900, Items.doubleWallUnit950, Items.doubleWallUnit1000, Items.doubleWallUnit1050, Items.doubleWallUnit1100, Items.doubleWallUnit1150, Items.doubleWallUnit1200]), catalog.registerCategory('corner-wall-unit', 'Corner Wall Unit', [Items.cornerWallUnit590]), catalog.registerCategory('blank-end-corner-wall-unit', 'Blank End Corner Wall Unit', [Items.blankEndCornerWallUnit600, Items.blankEndCornerWallUnit650, Items.blankEndCornerWallUnit700, Items.blankEndCornerWallUnit750, Items.blankEndCornerWallUnit800, Items.blankEndCornerWallUnit850, Items.blankEndCornerWallUnit900]) ] );
catalog.registerCategory('extra-units', 'Extra Units', [Items.washingMachine, Items.tumbleDryer, Items.fridgeFreezer, Items.americanFridgeFreezer, Items.cookerHousingUnit]);

export default catalog;
